package com.insurance.entities;
// Generated 20 mai 2019 23:32:14 by Hibernate Tools 5.4.2.Final

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Assureur generated by hbm2java
 */
@Entity
@Table(name="assureur", catalog="assurance")
public class Assureur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "code_assr", unique = true, nullable = false)
	private Integer codeAssr;
	@Column(name = "adr_assr")
	private String adrAssr;
	@Column(name = "nom_assr")
	private String nomAssr;
	@Column(name = "prenom_assr")
	private String prenomAssr;
	@Column(name = "tel_assr")
	private String telAssr;
	@Column(name = "login")
	private String login;
	@Column(name = "mdp")
	private String mdp;
	@Column(name = "mail_assr")
	private String mailAssr;
        
	@OneToMany(cascade = CascadeType.ALL)  
	@JoinColumn(name="ref_contrat")  
	private List<Contrat> contrats;
	
	
	public Assureur() {
	}

	public Assureur(String adrAssr, String nomAssr, String prenomAssr, String telAssr, String login, String mdp,
			String mailAssr,List<Contrat> contrats) {
		this.adrAssr = adrAssr;
		this.nomAssr = nomAssr;
		this.prenomAssr = prenomAssr;
		this.telAssr = telAssr;
		this.login = login;
		this.mdp = mdp;
		this.mailAssr = mailAssr;
		this.contrats=contrats;
	}

	public Integer getCodeAssr() {
		return this.codeAssr;
	}

	public void setCodeAssr(Integer codeAssr) {
		this.codeAssr = codeAssr;
	}

	public String getAdrAssr() {
		return this.adrAssr;
	}

	public void setAdrAssr(String adrAssr) {
		this.adrAssr = adrAssr;
	}

	public String getNomAssr() {
		return this.nomAssr;
	}

	public void setNomAssr(String nomAssr) {
		this.nomAssr = nomAssr;
	}

	public String getPrenomAssr() {
		return this.prenomAssr;
	}

	public void setPrenomAssr(String prenomAssr) {
		this.prenomAssr = prenomAssr;
	}

	public String getTelAssr() {
		return this.telAssr;
	}

	public void setTelAssr(String telAssr) {
		this.telAssr = telAssr;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	public String getMailAssr() {
		return this.mailAssr;
	}

	public void setMailAssr(String mailAssr) {
		this.mailAssr = mailAssr;
	}

	public List<Contrat> getContrats() {
		return contrats;
	}

	public void setContrats(List<Contrat> contrats) {
		this.contrats = contrats;
	}

	
}
