package com.insurance.entities;
// Generated 20 mai 2019 23:32:14 by Hibernate Tools 5.4.2.Final

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.*;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "assurance")
public class Client implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "code_cli", unique = true, nullable = false)
    private Integer codeCli;
    @Column(name = "adresse_cli", unique = false, nullable = false, length = 254)
    private String adresseCli;
    @Column(name = "datenais_cli", unique = false, nullable = false)
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date datenaisCli;
    @Column(name = "email_cli", unique = false, nullable = false, length = 254)
    private String emailCli;
    @Column(name = "fax_cli", unique = false, nullable = false, length = 254)
    private String faxCli;
    @Column(name = "tel_cli", unique = false, nullable = false, length = 254)
    private String telCli;
    @Column(name = "login_cli", unique = false, nullable = false, length = 254)
    private String loginCli;
    @Column(name = "mdp_cli", unique = false, nullable = false, length = 254)
    private String mdpCli;
    @Column(name = "permis", unique = false, nullable = false, length = 254)
    private String permis;
    @Column(name = "date_permis", unique = false, nullable = false)
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date datePermis;

    @OneToMany(mappedBy ="num_client" ,targetEntity = Contrat.class,cascade = CascadeType.ALL)
    private List<Contrat> contrats;

    
    public Client() {
    }

    public Client(String adresseCli, Date datenaisCli, String emailCli, String faxCli, String telCli, String loginCli,
            String mdpCli, String permis, Date datePermis) {
        super();
        this.adresseCli = adresseCli;
        this.datenaisCli = datenaisCli;
        this.emailCli = emailCli;
        this.faxCli = faxCli;
        this.telCli = telCli;
        this.loginCli = loginCli;
        this.mdpCli = mdpCli;
        this.permis = permis;
        this.datePermis = datePermis;
    }

    public Client(Integer codeCli, String adresseCli, Date datenaisCli, String emailCli, String faxCli, String telCli, String loginCli, String mdpCli, String permis, Date datePermis, List<Contrat> contrats) {
        this.codeCli = codeCli;
        this.adresseCli = adresseCli;
        this.datenaisCli = datenaisCli;
        this.emailCli = emailCli;
        this.faxCli = faxCli;
        this.telCli = telCli;
        this.loginCli = loginCli;
        this.mdpCli = mdpCli;
        this.permis = permis;
        this.datePermis = datePermis;
        this.contrats = contrats;
    }

    
    public Integer getCodeCli() {
        return this.codeCli;
    }

    public void setCodeCli(Integer codeCli) {
        this.codeCli = codeCli;
    }

    public String getAdresseCli() {
        return this.adresseCli;
    }

    public void setAdresseCli(String adresseCli) {
        this.adresseCli = adresseCli;
    }

    public Date getDatenaisCli() {
        return this.datenaisCli;
    }

    public void setDatenaisCli(Date datenaisCli) {
        this.datenaisCli = datenaisCli;
    }

    public String getEmailCli() {
        return this.emailCli;
    }

    public void setEmailCli(String emailCli) {
        this.emailCli = emailCli;
    }

    public String getFaxCli() {
        return this.faxCli;
    }

    public void setFaxCli(String faxCli) {
        this.faxCli = faxCli;
    }

    public String getTelCli() {
        return this.telCli;
    }

    public void setTelCli(String telCli) {
        this.telCli = telCli;
    }

    public String getLoginCli() {
        return this.loginCli;
    }

    public void setLoginCli(String loginCli) {
        this.loginCli = loginCli;
    }

    public String getMdpCli() {
        return this.mdpCli;
    }

    public void setMdpCli(String mdpCli) {
        this.mdpCli = mdpCli;
    }

    public String getPermis() {
        return this.permis;
    }

    public void setPermis(String permis) {
        this.permis = permis;
    }

    public Date getDatePermis() {
        return this.datePermis;
    }

    public void setDatePermis(Date datePermis) {
        this.datePermis = datePermis;
    }

    public List<Contrat> getContrats() {
        return contrats;
    }

    public void setContrats(List<Contrat> contrats) {
        this.contrats = contrats;
    }

   

    @Override
    public String toString() {
        return "Client{" + "codeCli=" + codeCli + ", adresseCli=" + adresseCli + ", datenaisCli=" + datenaisCli + ", emailCli=" + emailCli + ", faxCli=" + faxCli + ", telCli=" + telCli + ", loginCli=" + loginCli + ", mdpCli=" + mdpCli + ", permis=" + permis + ", datePermis=" + datePermis + ", contrats=" + contrats + '}';
    }

 
}
