package com.insurance.entities;
// Generated 20 mai 2019 23:32:14 by Hibernate Tools 5.4.2.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Garantie generated by hbm2java
 */
@Entity
@Table(name="garantie", catalog="assurance")
public class Garantie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "code_garantie", unique = true, nullable = false)
	private Integer codeGarantie;
	@Column(name = "base", unique = false, nullable = false)
	private Integer base;
	@Column(name = "lib_garantie", unique = false, nullable = false)
	private String libGarantie;
	@Column(name = "forfait", unique = false, nullable = false)
	private Integer forfait;
	@Column(name = "taux", unique = false, nullable = false)
	private Integer taux;

	public Garantie() {
	}

	public Garantie(Integer base, String libGarantie, Integer forfait, Integer taux) {
		this.base = base;
		this.libGarantie = libGarantie;
		this.forfait = forfait;
		this.taux = taux;
	}

	public Integer getCodeGarantie() {
		return this.codeGarantie;
	}

	public void setCodeGarantie(Integer codeGarantie) {
		this.codeGarantie = codeGarantie;
	}

	public Integer getBase() {
		return this.base;
	}

	public void setBase(Integer base) {
		this.base = base;
	}

	public String getLibGarantie() {
		return this.libGarantie;
	}

	public void setLibGarantie(String libGarantie) {
		this.libGarantie = libGarantie;
	}

	public Integer getForfait() {
		return this.forfait;
	}

	public void setForfait(Integer forfait) {
		this.forfait = forfait;
	}

	public Integer getTaux() {
		return this.taux;
	}

	public void setTaux(Integer taux) {
		this.taux = taux;
	}

}
