package com.insurance.entities;
// Generated 20 mai 2019 23:32:14 by Hibernate Tools 5.4.2.Final

import javax.persistence.Embeddable;

/**
 * GarantieVehiculeId generated by hbm2java
 */
@Embeddable
public class GarantieVehiculeId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String immatOuMoto;
	private int codeGarantie;

	public GarantieVehiculeId() {
	}

	public GarantieVehiculeId(String immatOuMoto, int codeGarantie) {
		this.immatOuMoto = immatOuMoto;
		this.codeGarantie = codeGarantie;
	}

	public String getImmatOuMoto() {
		return this.immatOuMoto;
	}

	public void setImmatOuMoto(String immatOuMoto) {
		this.immatOuMoto = immatOuMoto;
	}

	public int getCodeGarantie() {
		return this.codeGarantie;
	}

	public void setCodeGarantie(int codeGarantie) {
		this.codeGarantie = codeGarantie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GarantieVehiculeId))
			return false;
		GarantieVehiculeId castOther = (GarantieVehiculeId) other;

		return ((this.getImmatOuMoto() == castOther.getImmatOuMoto()) || (this.getImmatOuMoto() != null
				&& castOther.getImmatOuMoto() != null && this.getImmatOuMoto().equals(castOther.getImmatOuMoto())))
				&& (this.getCodeGarantie() == castOther.getCodeGarantie());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getImmatOuMoto() == null ? 0 : this.getImmatOuMoto().hashCode());
		result = 37 * result + this.getCodeGarantie();
		return result;
	}

}
