package com.insurance.entities;
// Generated 20 mai 2019 23:32:14 by Hibernate Tools 5.4.2.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GarantieVehicule generated by hbm2java
 */
@Entity
@Table(name="garantieVehicule", catalog="assurance")
public class GarantieVehicule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	private GarantieVehiculeId id;
	@Column(name = "montant_garantie", unique = false, nullable = false)
	private Integer montantGarantie;

	public GarantieVehicule() {
	}

	public GarantieVehicule(GarantieVehiculeId id) {
		this.id = id;
	}

	public GarantieVehicule(GarantieVehiculeId id, Integer montantGarantie) {
		this.id = id;
		this.montantGarantie = montantGarantie;
	}

	public GarantieVehiculeId getId() {
		return this.id;
	}

	public void setId(GarantieVehiculeId id) {
		this.id = id;
	}

	public Integer getMontantGarantie() {
		return this.montantGarantie;
	}

	public void setMontantGarantie(Integer montantGarantie) {
		this.montantGarantie = montantGarantie;
	}

}
