package com.insurance.entities;
// Generated 20 mai 2019 23:32:14 by Hibernate Tools 5.4.2.Final

import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Marque generated by hbm2java
 */
@Entity
@Table(name = "marque", catalog = "assurance")
public class Marque implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "code_marq", unique = true, nullable = false)
    private Integer codeMarq;
    @Column(name = "lib_marq")
    private String libMarq;

    @OneToMany(mappedBy = "marque", targetEntity = Vehicule.class, cascade = CascadeType.ALL)
    private List<Vehicule> vehicules;

    public Marque() {
    }

    public Marque(String libMarq) {
        this.libMarq = libMarq;
    }

    public Integer getCodeMarq() {
        return this.codeMarq;
    }

    public void setCodeMarq(Integer codeMarq) {
        this.codeMarq = codeMarq;
    }

    public String getLibMarq() {
        return this.libMarq;
    }

    public void setLibMarq(String libMarq) {
        this.libMarq = libMarq;
    }

    public List<Vehicule> getVehicules() {
        return vehicules;
    }

    public void setVehicules(List<Vehicule> vehicules) {
        this.vehicules = vehicules;
    }
    
    
    

}
