package com.insurance.entities;
// Generated 20 mai 2019 23:32:14 by Hibernate Tools 5.4.2.Final

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OrderColumn;
import javax.persistence.Table;

/**
 * Pack generated by hbm2java
 */
@Entity
@Table(name="pack", catalog="assurance")
public class Pack implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_pack", unique = true, nullable = false)
	private Integer idPack;
	@Column(name = "lib_pack", unique = true,nullable = false)
	private String libPack;
	@Column(name = "vol")
	private Boolean vol;
	@Column(name = "incendie")
	private Boolean incendie;
	@Column(name = "brisGlaces")
	private Boolean brisGlaces;
	@Column(name = "personnesTransportee")
	private Boolean personnesTransportee;
	@Column(name = "respCivil")
	private Boolean respCivil;
	@Column(name = "protJuri")
	private Boolean protJuri;
	@Column(name = "panneMecanique")
	private Boolean panneMecanique;
        
	@OneToMany(cascade = CascadeType.ALL)  
	@JoinColumn(name="ref_contrat")  
	private List<Contrat> contrats;

	public Pack() {
	}

	public Pack(String libPack, Boolean vol, Boolean incendie, Boolean brisGlaces, Boolean personnesTransportee,
			Boolean respCivil, Boolean protJuri, Boolean panneMecanique,List<Contrat> contrats) {
		this.libPack = libPack;
		this.vol = vol;
		this.incendie = incendie;
		this.brisGlaces = brisGlaces;
		this.personnesTransportee = personnesTransportee;
		this.respCivil = respCivil;
		this.protJuri = protJuri;
		this.panneMecanique = panneMecanique;
		this.contrats=contrats;
	}

	public Integer getIdPack() {
		return this.idPack;
	}

	public void setIdPack(Integer idPack) {
		this.idPack = idPack;
	}

	public String getLibPack() {
		return this.libPack;
	}

	public void setLibPack(String libPack) {
		this.libPack = libPack;
	}

	public Boolean getVol() {
		return this.vol;
	}

	public void setVol(Boolean vol) {
		this.vol = vol;
	}

	public Boolean getIncendie() {
		return this.incendie;
	}

	public void setIncendie(Boolean incendie) {
		this.incendie = incendie;
	}

	public Boolean getBrisGlaces() {
		return this.brisGlaces;
	}

	public void setBrisGlaces(Boolean brisGlaces) {
		this.brisGlaces = brisGlaces;
	}

	public Boolean getPersonnesTransportee() {
		return this.personnesTransportee;
	}

	public void setPersonnesTransportee(Boolean personnesTransportee) {
		this.personnesTransportee = personnesTransportee;
	}

	public Boolean getRespCivil() {
		return this.respCivil;
	}

	public void setRespCivil(Boolean respCivil) {
		this.respCivil = respCivil;
	}

	public Boolean getProtJuri() {
		return this.protJuri;
	}

	public void setProtJuri(Boolean protJuri) {
		this.protJuri = protJuri;
	}

	public Boolean getPanneMecanique() {
		return this.panneMecanique;
	}

	public void setPanneMecanique(Boolean panneMecanique) {
		this.panneMecanique = panneMecanique;
	}

	public List<Contrat> getContrats() {
		return contrats;
	}

	public void setContrats(List<Contrat> contrats) {
		this.contrats = contrats;
	}
	
	

}
