package com.insurance.entities;
// Generated 20 mai 2019 23:32:14 by Hibernate Tools 5.4.2.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Personne generated by hbm2java
 */
@Entity
@Table(name="personne", catalog="assurance")
public class Personne extends Client implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id 
	private Integer codeCli;
	@Column(name = "cin", unique = false, nullable = false, length = 254)
	private String cin;
	@Column(name = "nom_cli", unique = false, nullable = false, length = 254)
	private String nomCli;
	@Column(name = "prenom_cli", unique = false, nullable = false, length = 254)
	private String prenomCli;

	public Personne() {
	}

	public Personne(String adresseCli, Date datenaisCli, String emailCli, String faxCli, String telCli, String loginCli,
			String mdpCli, String permis, Date datePermis ,String cin, String nomCli, String prenomCli) {
		super(adresseCli,datenaisCli,emailCli,faxCli,telCli,loginCli,mdpCli,permis,datePermis);
		this.cin = cin;
		this.nomCli = nomCli;
		this.prenomCli = prenomCli;
	}

	public Integer getCodeCli() {
		return this.codeCli;
	}

	public void setCodeCli(Integer codeCli) {
		this.codeCli = codeCli;
	}

	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	public String getNomCli() {
		return this.nomCli;
	}

	public void setNomCli(String nomCli) {
		this.nomCli = nomCli;
	}

	public String getPrenomCli() {
		return this.prenomCli;
	}

	public void setPrenomCli(String prenomCli) {
		this.prenomCli = prenomCli;
	}

}
