package com.insurance.entities;
// Generated 20 mai 2019 23:32:14 by Hibernate Tools 5.4.2.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Piece generated by hbm2java
 */
@Entity
@Table(name="piece", catalog="assurance")
public class Piece implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "code_piece", unique = true, nullable = false)
	private Integer codePiece;
	
	private int codeSinistre;
	@Column(name = "lib_piece", unique = false, nullable = false, length = 254)
	private String libPiece;
	@Column(name = "file", unique = false, nullable = false, length = 254)
	private Byte file;

	public Piece() {
	}

	public Piece(int codeSinistre) {
		this.codeSinistre = codeSinistre;
	}

	public Piece(int codeSinistre, String libPiece, Byte file) {
		this.codeSinistre = codeSinistre;
		this.libPiece = libPiece;
		this.file = file;
	}

	public Integer getCodePiece() {
		return this.codePiece;
	}

	public void setCodePiece(Integer codePiece) {
		this.codePiece = codePiece;
	}

	public int getCodeSinistre() {
		return this.codeSinistre;
	}

	public void setCodeSinistre(int codeSinistre) {
		this.codeSinistre = codeSinistre;
	}

	public String getLibPiece() {
		return this.libPiece;
	}

	public void setLibPiece(String libPiece) {
		this.libPiece = libPiece;
	}

	public Byte getFile() {
		return this.file;
	}

	public void setFile(Byte file) {
		this.file = file;
	}

}
