package com.insurance.entities;
// Generated 20 mai 2019 23:32:14 by Hibernate Tools 5.4.2.Final

import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usag generated by hbm2java
 */
@Entity
@Table(name = "usag", catalog = "assurance")
public class Usag implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_use", unique = true, nullable = false)
    private Integer idUse;
    @Column(name = "type", unique = false, nullable = false, length = 254)
    private String type;
    @Column(name = "lib_usage", unique = false, nullable = false, length = 254)
    private String libUsage;

    @OneToMany(mappedBy = "marque", targetEntity = Vehicule.class, cascade = CascadeType.ALL)
    private List<Vehicule> vehicules;

    public Usag() {
    }

    public Usag(String type, String libUsage) {
        this.type = type;
        this.libUsage = libUsage;
    }

    public Usag(Integer idUse, String type, String libUsage, List<Vehicule> vehicules) {
        this.idUse = idUse;
        this.type = type;
        this.libUsage = libUsage;
        this.vehicules = vehicules;
    }

    public Integer getIdUse() {
        return this.idUse;
    }

    public void setIdUse(Integer idUse) {
        this.idUse = idUse;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getLibUsage() {
        return this.libUsage;
    }

    public void setLibUsage(String libUsage) {
        this.libUsage = libUsage;
    }

    public List<Vehicule> getVehicules() {
        return vehicules;
    }

    public void setVehicules(List<Vehicule> vehicules) {
        this.vehicules = vehicules;
    }

}
