package com.insurance.entities;
// Generated 20 mai 2019 23:32:14 by Hibernate Tools 5.4.2.Final

import java.sql.Date;
import javax.persistence.CascadeType;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "assurance")
public class Utilisateur implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id_utilisateur", unique = true, nullable = false)
    private int idUtilisateur;

    @Column(name = "login")
    private String login;

    @Column(name = "password")
    private String password;

    @Column(name = "date_creation")
    private Date dateCreation;

    @Column(name = "date_expiration")
    private Date dateExpiration;

    @Column(name = "role_utilisateur")
    private String roleUtilisateur;

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "id_client", updatable = true, nullable = true, insertable = true)
    private Client client;

    public Utilisateur() {
    }

    public Utilisateur(int idUtilisateur, String login, String password, Date dateCreation, Date dateExpiration, String roleUtilisateur) {
        this.idUtilisateur = idUtilisateur;
        this.login = login;
        this.password = password;
        this.dateCreation = dateCreation;
        this.dateExpiration = dateExpiration;
        this.roleUtilisateur = roleUtilisateur;
    }

    public int getIdUtilisateur() {
        return idUtilisateur;
    }

    public void setIdUtilisateur(int idUtilisateur) {
        this.idUtilisateur = idUtilisateur;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Date getDateCreation() {
        return dateCreation;
    }

    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }

    public Date getDateExpiration() {
        return dateExpiration;
    }

    public void setDateExpiration(Date dateExpiration) {
        this.dateExpiration = dateExpiration;
    }

    public String getRoleUtilisateur() {
        return roleUtilisateur;
    }

    public void setRoleUtilisateur(String roleUtilisateur) {
        this.roleUtilisateur = roleUtilisateur;
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    @Override
    public String toString() {
        return "Utilisateur{" + "idUtilisateur=" + idUtilisateur + ", login=" + login + ", password=" + password + ", dateCreation=" + dateCreation + ", dateExpiration=" + dateExpiration + ", roleUtilisateur=" + roleUtilisateur + '}';
    }

}
