package com.insurance.entities;
// Generated 20 mai 2019 23:32:14 by Hibernate Tools 5.4.2.Final

import java.util.Date;
import javax.persistence.CascadeType;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * Vehicule generated by hbm2java
 */
@Entity
@Table(name = "vehicule", catalog = "assurance")
public class Vehicule implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "immat_ou_moto", unique = true, nullable = false)
    private Integer immatOuMoto;
    
    @Column(name = "num_attest")
    private Integer numAttest;
    @Column(name = "puiss_adm")
    private Integer puissAdm;
    @Column(name = "val_declaree")
    private Integer valDeclaree;
    @Column(name = "date_mec")
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date dateMec;
    @Column(name = "val_neuve")
    private Integer valNeuve;
    @Column(name = "val_venale")
    private Integer valVenale;
    @Column(name = "quittance")
    private Integer quittance;
    @Column(name = "carburant", length = 254)
    private String carburant;
    @Column(name = "genre", length = 254)
    private String genre;
    @Column(name = "remorque", length = 254)
    private String remorque;
    @Column(name = "taux_reduction")
    private Integer tauxReduction;
    @Column(name = "nbr_places")
    private Integer nbrPlaces;

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "code_marq")
    private Marque marque;

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "id_use")
    private Usag usag;

    public Vehicule() {
    }

    public Vehicule(Marque marque) {
        this.marque = marque;
    }

    public Vehicule(Integer immatOuMoto, Integer numAttest, Integer puissAdm, Integer valDeclaree, Date dateMec, Integer valNeuve, Integer valVenale, Integer quittance, String carburant, String genre, String remorque, Integer tauxReduction, Integer nbrPlaces, Marque marque) {
        this.immatOuMoto = immatOuMoto;
        this.numAttest = numAttest;
        this.puissAdm = puissAdm;
        this.valDeclaree = valDeclaree;
        this.dateMec = dateMec;
        this.valNeuve = valNeuve;
        this.valVenale = valVenale;
        this.quittance = quittance;
        this.carburant = carburant;
        this.genre = genre;
        this.remorque = remorque;
        this.tauxReduction = tauxReduction;
        this.nbrPlaces = nbrPlaces;
        this.marque = marque;
    }

    public Vehicule(Integer immatOuMoto, Integer numAttest, Integer puissAdm, Integer valDeclaree, Date dateMec, Integer valNeuve, Integer valVenale, Integer quittance, String carburant, String genre, String remorque, Integer tauxReduction, Integer nbrPlaces, Marque marque, Usag usag) {
        this.immatOuMoto = immatOuMoto;
        this.numAttest = numAttest;
        this.puissAdm = puissAdm;
        this.valDeclaree = valDeclaree;
        this.dateMec = dateMec;
        this.valNeuve = valNeuve;
        this.valVenale = valVenale;
        this.quittance = quittance;
        this.carburant = carburant;
        this.genre = genre;
        this.remorque = remorque;
        this.tauxReduction = tauxReduction;
        this.nbrPlaces = nbrPlaces;
        this.marque = marque;
        this.usag = usag;
    }

    public Integer getImmatOuMoto() {
        return this.immatOuMoto;
    }

    public void setImmatOuMoto(Integer immatOuMoto) {
        this.immatOuMoto = immatOuMoto;
    }

    public Marque getMarque() {
        return marque;
    }

    public void setMarque(Marque marque) {
        this.marque = marque;
    }

    public Usag getUsag() {
        return usag;
    }

    public void setUsag(Usag usag) {
        this.usag = usag;
    }

    public Integer getNumAttest() {
        return this.numAttest;
    }

    public void setNumAttest(Integer numAttest) {
        this.numAttest = numAttest;
    }

    public Integer getPuissAdm() {
        return this.puissAdm;
    }

    public void setPuissAdm(Integer puissAdm) {
        this.puissAdm = puissAdm;
    }

    public Integer getValDeclaree() {
        return this.valDeclaree;
    }

    public void setValDeclaree(Integer valDeclaree) {
        this.valDeclaree = valDeclaree;
    }

    public Date getDateMec() {
        return this.dateMec;
    }

    public void setDateMec(Date dateMec) {
        this.dateMec = dateMec;
    }

    public Integer getValNeuve() {
        return this.valNeuve;
    }

    public void setValNeuve(Integer valNeuve) {
        this.valNeuve = valNeuve;
    }

    public Integer getValVenale() {
        return this.valVenale;
    }

    public void setValVenale(Integer valVenale) {
        this.valVenale = valVenale;
    }

    public Integer getQuittance() {
        return this.quittance;
    }

    public void setQuittance(Integer quittance) {
        this.quittance = quittance;
    }

    public String getCarburant() {
        return this.carburant;
    }

    public void setCarburant(String carburant) {
        this.carburant = carburant;
    }

    public String getGenre() {
        return this.genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public String getRemorque() {
        return this.remorque;
    }

    public void setRemorque(String remorque) {
        this.remorque = remorque;
    }

    public Integer getTauxReduction() {
        return this.tauxReduction;
    }

    public void setTauxReduction(Integer tauxReduction) {
        this.tauxReduction = tauxReduction;
    }

    public Integer getNbrPlaces() {
        return this.nbrPlaces;
    }

    public void setNbrPlaces(Integer nbrPlaces) {
        this.nbrPlaces = nbrPlaces;
    }

}
